main: net.illager.timeout.Timeout
name: Timeout
api-version: @API-VERSION@
version: @VERSION@
commands:
  revive:
    description: Revive a deathbanned player
    usage: /revive <username> [<username> ...]
    permission: timeout.revive
    permission-message: You are not allowed to revive deathbanned players
